#!/bin/bash -eu

# shellcheck source=/opt/atl_manage/events/install-post/.common.sh
. "$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"/../.common.sh
# Only do maintenance check if we're running interactively.
if [ -t 1 ]; then atl_maintenance check; fi
