#!/bin/bash -eu

# shellcheck source=/opt/atl_manage/events/.common.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/../.common.sh

require_app jira confluence

if [[ -v ATL_BANNERTEXT ]]; then
	log "Setting banner text: $ATL_BANNERTEXT"
	atl_pg_set "$ATL_PRODUCT" bannertext "$ATL_BANNERTEXT" | atl_psql -tXAq
fi
if [[ -v ATL_BANNERCOLOUR ]]; then
	log "Setting banner colour: $ATL_BANNERCOLOUR"
	atl_pg_set "$ATL_PRODUCT" bannercolour "$ATL_BANNERCOLOUR" | atl_psql -tXAq
fi
