#!/bin/bash -eu
# shellcheck source=/opt/atl_manage/events/install-pre/.common.sh
. "$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"/.common.sh

if [[ -v ATL_REPLICATION_PRIMARY && $ATL_REPLICATION_PRIMARY = true || -v ATL_REPLICATION_STANDBY && $ATL_REPLICATION_STANDBY = true ]]; then
	addguard replication
fi
