#!/bin/bash -eu

# shellcheck source=/opt/atl_manage/backupmirror/common_source.sh
. "$ATL_MANAGE/backupmirror/common.sh"

#shellcheck source=/opt/atl_manage/lib/remote/run
. "$ATL_MANAGE/lib/remote/run" "$@"
