#!/bin/bash -eu

obsolete() {
	fail "The 'atl' patch is present in your patchqueue. It should have been moved to 'app'"
}

install-post() { obsolete; }
upgrade-stopped-pre() { obsolete; }
upgrade-running-pre() { obsolete; }

# shellcheck source=/opt/atl_manage/events/install-post/.common.sh
. "$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"/.common.sh
