#!/bin/bash

set -euo pipefail

install-post() {
	# The actual php package install is done in atl_deploy. This postinst script configured php-fpm pools
	if [[ ${ATL_PRODUCT_RUNTIME_TECHNOLOGY:-} =~ php([0-9\.]+)-fpm ]]; then
		local phpver destdir
		phpver="${BASH_REMATCH[1]}"

		srcfile="$ATL_APPDIR/php/php-fpm-pool.conf"
		destdir="/etc/php/$phpver/fpm/pool.d"
		destfile="$destdir/$ATL_APPDOMAIN.conf"


		if [[ ${ATL_MULTITENANT:-} = true ]]; then
			log "Multitenant: we assume each tenant has symlinked something into $destdir"
			return
		fi

		[[ -f "$srcfile" ]] || fail "Missing '$srcfile'"
		[[ -d $destdir ]] || fail "Missing '$destdir'. This is expected to have been provided by the ${ATL_PRODUCT_RUNTIME_TECHNOLOGY} Debian package"
		log "Symlinking $ATL_PRODUCT_RUNTIME_TECHNOLOGY pool config file $destfile"

		# We may have multiple versions of (say) Jethro installed, but only one php-fpm. The first one to install
		# $destfile 'wins'. In practice, all versions of Jethro will have identical $srcfile's, saying "load pools from
		# ATL_DATADIR_BASE/*/conf/php-fpm.conf"
		if [[ ! -f "$destfile" ]]; then
			ln -s "$srcfile" "$destfile"
		else
			echo "$destfile already exists. Not rewriting"
		fi
	else
		fail "Invaid ATL_PRODUCT_RUNTIME_TECHNOLOGY value '$ATL_PRODUCT_RUNTIME_TECHNOLOGY'. It must be in format 'phpX.X-fpm'"
	fi
}

enabled() {
	# ATL_BACKUP_TYPES=tarsnap is typically set explicitly in the app profile
	[[ ${ATL_PRODUCT_RUNTIME_TECHNOLOGY:-} =~ php ]]
}

# shellcheck source=/opt/atl_manage/events/install-post/.webserver-common.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/.webserver-common.sh
# shellcheck source=/opt/atl_manage/events/install-post/.common.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/.common.sh
